<?php


// not read me
//define( 'TWITTWER_CONSUMER_KEY', 'KqNOHeJZmkoz9nlyYInGn8Hgu');
//define( 'TWITTWER_CONSUMER_SECRET', 'eTOfPfOxFP8pwAKjMWUNKOa8uHjkC20OA2o57hnQ7JhiGhIM9J');
//define( 'TWITTWER_ACCESS_TOKEN', '113935838-4hNfKs6e4V71idIuYmuXSsEdoeIxe5YNC66FJpmE');
//define( 'TWITTWER_ACCESS_TOKEN_SECRET', 'XUn29nLefFRE4botqUQzjvzLiM8VoJE5SfeHpZEr1UrRr');

define( 'TWITTWER_CONSUMER_KEY', 'PfXJElI5qyTaqCufYRfOMbJdu');
define( 'TWITTWER_CONSUMER_SECRET', 'zpk6DCML0wtfCwxcHBbXRGiuESVy06lKpyye4cUMOvC7NWjw7k');
define( 'TWITTWER_ACCESS_TOKEN', '113935838-NDxwqFZgKwyrhUtDCvZ3oV2m9ki8iqJZzsz1JeQy');
define( 'TWITTWER_ACCESS_TOKEN_SECRET', 'PBgC6yG4nBcraHWvW6DR9z3fLw1Z8HrcOOMcqJ4bnAPxa');
